spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckInterval: 20s
  application:
    name: consul_demo_api
  messages:
    basename: messages/messages
server:
  servlet:
    context-path: /petclinicapi/
logging:
  level:
    org:
      springframework: INFO
petclinic:
  security:
    enable: true
