spring:
  profiles:
    active: hsqldb,spring-data-jpa
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        prefix: config/application
        defaultContext: apps
        profileSeparator: '::'
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckInterval: 20s
  application:
    name: consul_demo_api
  messages:
    basename: messages/messages
server:
  servlet:
    context-path: /petclinicapi/
logging:
  level:
    org:
      springframework: INFO
petclinic:
  security:
    enable: true
